### ISSUE TITLE
TODO#2: Crear el usuario admin

### ISSUE THREAD

**Issue by thatmare** [thatmare/Burger-Queen-API#3]
- [x] Crear una función de routes/users.js llamada initAdminUser que recibe dos parámetros: app y next.
- [x] Esta función primero corrobora que no haya ningún usuario y, de no ser así, lo crea.
- [x] El resultado debe ser usuaria con rol de administradora en la base de datos. 
- [x] Corroborar métodos de Express y Mongoose.
