### ISSUE TITLE
TODO#3: Implementar autenticación de usuaria

### ISSUE THREAD

**Issue by thatmare** [thatmare/Burger-Queen-API#5]
- [x] Verificar que email y password coinciden con los datos de alguna usuaria en db.
- [x] De ser así, generar JWT y enviarlo en la respuesta.
- [x] Buscar tutoriales de autenticación con JWT y node/express.
