### ISSUE TITLE
TODO#4: Implemenentar middleware de autenticación

### ISSUE THREAD

**Issue by thatmare** [thatmare/Burger-Queen-API#9]
- [x] Entender el concepto de middleware en express.
- [x] Verificar identidad del usuario usando `decodeToken.uid`
- [x] Decidir por la informacion del request si la usuaria esta autenticada.
- [x] Decidir por la informacion del request si la usuaria es admin.
